/*
 * =====================================================================================
 *
 *       Filename:  ydb_protocol.h
 *
 *    Description:
 *
 *        Version:  1.0
 *        Created:  2014/06/24 10时06分28秒
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  YOUR NAME (),
 *   Organization:
 *
 * =====================================================================================
 */
#ifndef _YDB_PROTOCOL_H_
#define _YDB_PROTOCOL_H_
#ifdef __cplusplus
extern "C" {
#endif

#define YDB_VERSION 1

#define YDB_GROUPNAME_LEN 7
#define YDB_MACHINEID_LEN 7

#define YDB_REGEDIT_STORAGE 1
#define YDB_HEARTBEAT_STORAGE 2
#define YDB_SHUTDOWN_STORAGE 3

#define YDB_TRACKER_QUERY_UPLOAD_STORAGE 4
#define YDB_TRACKER_QUERY_SELECT_STORAGE 5
#define YDB_TRACKER_QUERY_DELETE_STORAGE 6
#define YDB_TRACKER_QUERY_MODIFY_STORAGE 7

#define YDB_QUERY_SYNC_STORAGES 8
#define YDB_QUERY_STORAGE_STATUS 9

#define YDB_STORAGE_NORMAL 0
#define YDB_STORAGE_INITING 1
#define YDB_STORAGE_SYNCING 2
#define YDB_STORAGE_RUNNING 3
#define YDB_STORAGE_CLOSING 4
#define YDB_STORAGE_CLOSED 5

#define YDB_STORAGE_UPLOAD 0
#define YDB_STORAGE_FIND 1
#define YDB_STORAGE_MODIFY 2
#define YDB_STORAGE_DELETE 3
#define YDB_STORAGE_SYNC 4

#define YDB_FILENAME_SUFFIX_SIZE 7

#define YDB_HASHCODE_SIZE 64

#define YDB_CHUNKFILE_MEMADATA_SIZE \
    sizeof(char) + sizeof(u32_t) + sizeof(u64_t) + sizeof(u64_t) \
    + sizeof(u32_t) + sizeof(u64_t) + sizeof(u64_t) \
    + YDB_HASHCODE_SIZE

#define YDB_CHUNKFILE_OFFSET_ISDELETE 0
#define YDB_CHUNKFILE_SIZE_ISDELETE sizeof(char)

#define YDB_CHUNKFILE_OFFSET_OPVER \
    YDB_CHUNKFILE_OFFSET_ISDELETE + YDB_CHUNKFILE_SIZE_ISDELETE
#define YDB_CHUNKFILE_SIZE_OPVER sizeof(u32_t)

#define YDB_CHUNKFILE_OFFSET_VERSION \
    YDB_CHUNKFILE_OFFSET_OPVER + YDB_CHUNKFILE_SIZE_OPVER
#define YDB_CHUNKFILE_SIZE_VERSION sizeof(u32_t)

#define YDB_CHUNKFILE_OFFSET_CREATETIME \
    YDB_CHUNKFILE_OFFSET_VERSION + YDB_CHUNKFILE_SIZE_VERSION
#define YDB_CHUNKFILE_SIZE_CREATETIME sizeof(u64_t)

#define YDB_CHUNKFILE_OFFSET_LASTMODIFYTIME \
    YDB_CHUNKFILE_OFFSET_CREATETIME + YDB_CHUNKFILE_SIZE_CREATETIME
#define YDB_CHUNKFILE_SIZE_LASTMODIFYTIME sizeof(u64_t)

#define YDB_CHUNKFILE_OFFSET_TOTALLEN \
    YDB_CHUNKFILE_OFFSET_LASTMODIFYTIME + YDB_CHUNKFILE_SIZE_LASTMODIFYTIME
#define YDB_CHUNKFILE_SIZE_TOTALLEN sizeof(u64_t)

#define YDB_CHUNKFILE_OFFSET_REALSIZE \
    YDB_CHUNKFILE_OFFSET_TOTALLEN + YDB_CHUNKFILE_SIZE_TOTALLEN
#define YDB_CHUNKFILE_SIZE_REALSIZE sizeof(u64_t)

#define YDB_CHUNKFILE_OFFSET_SUFFIX \
    YDB_CHUNKFILE_OFFSET_REALSIZE + YDB_CHUNKFILE_SIZE_REALSIZE
#define YDB_CHUNKFILE_SIZE_SUFFIX YDB_FILENAME_SUFFIX_SIZE

#define YDB_CHUNKFILE_OFFSET_HASHCODE \
    YDB_CHUNKFILE_OFFSET_SUFFIX + YDB_CHUNKFILE_SIZE_SUFFIX
#define YDB_CHUNKFILE_SIZE_HASHCODE YDB_HASHCODE_SIZE


#define YDB_CHUNKFILE_OFFSET_BODY \
    YDB_CHUNKFILE_OFFSET_HASHCODE + YDB_CHUNKFILE_SIZE_HASHCODE


#define YDB_TRANSPORT_UPLOAD_OFFSET_HASSUFFIX 0
#define YDB_TRANSPORT_UPLOAD_SIZE_HASSUFFIX 1

#define YDB_TRANSPORT_UPLOAD_OFFSET_SUFFIX \
    YDB_TRANSPORT_UPLOAD_OFFSET_HASSUFFIX + YDB_TRANSPORT_UPLOAD_SIZE_HASSUFFIX
#define YDB_TRANSPORT_UPLOAD_SIZE_SUFFIX YDB_FILENAME_SUFFIX

#define YDB_TRANSPORT_UPLOAD_OFFSET_BODYBUFFER(has_suffix) \
    has_suffix \
    ? YDB_TRANSPORT_UPLOAD_OFFSET_SUFFIX + YDB_TRANSPORT_UPLOAD_SIZE_SUFFIX \
    YDB_TRANSPORT_UPLOAD_OFFSET_HASSUFFIX + YDB_TRANSPORT_UPLOAD_SIZE_HASSUFFIX


#ifdef __cplusplus
}
#endif
#endif
